// This rendering regression runs against Vite dev so the production star module can be imported directly.
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--enable-webgl','--ignore-gpu-blocklist']});
try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto((process.env.TEST_DEV_URL||'http://127.0.0.1:5173')+'/');await page.waitForSelector('.ready');const result=await page.evaluate(async()=>{
 const THREE=await import('/node_modules/three/build/three.module.js'),{createStarfield}=await import('/src/starfield.js');const results=[];
 for(const logarithmicDepthBuffer of [false,true]){const scene=new THREE.Scene(),sky=createStarfield(scene);await sky.ready;const renderer=new THREE.WebGLRenderer({preserveDrawingBuffer:true,logarithmicDepthBuffer});renderer.setSize(400,400);renderer.setClearColor(0x000000);const camera=new THREE.PerspectiveCamera(75,1,.000001,100000),target=new THREE.WebGLRenderTarget(400,400);const render=()=>{renderer.setRenderTarget(target);renderer.render(scene,camera);const pixels=new Uint8Array(400*400*4);renderer.readRenderTargetPixels(target,0,0,400,400,pixels);return pixels;};const original=render();camera.position.set(450000,-22000,980000);const translated=render();camera.rotation.y=.4;const rotated=render();results.push({logarithmicDepthBuffer,lit:original.filter((x,i)=>i%4!==3&&x>0).length,translationDifferences:original.filter((x,i)=>x!==translated[i]).length,rotationDifferences:original.filter((x,i)=>x!==rotated[i]).length});target.dispose();sky.stars.geometry.dispose();sky.stars.material.map.dispose();sky.stars.material.dispose();renderer.dispose();}
 return results;
});for(const r of result){assert.ok(r.lit>100,'catalog stars are visible');assert.equal(r.translationDifferences,0,'camera translation must not shift or resize stars');assert.ok(r.rotationDifferences>100,'camera rotation changes the visible sky');}assert.deepEqual(errors,[]);console.log('Distant sky has pixel-identical rendering across camera translations, with normal and logarithmic depth:',result);}finally{await browser.close();}
